name: Quality

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    env:
      SITE_URL: https://www.pasiekanatury.com
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: npm
      - run: npm ci
      - run: npm run quality
